services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  sender:
    build:
      context: .
      dockerfile: Dockerfile.sender
    depends_on:
      - rabbitmq
      - redis
    environment:
      - RABBITMQ_HOST=rabbitmq
      - QUEUE_NAME=${QUEUE_NAME}
      - REDIS_HOST=redis
      - MEAN_PROCESSING_TIME=${MEAN_PROCESSING_TIME}
      - FAILURE_RATE=${FAILURE_RATE}
    deploy:
      replicas: 1
    restart: always

  monitor:
    build:
      context: .
      dockerfile: Dockerfile.monitor
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - MONITOR_UPDATE_INTERVAL=${MONITOR_UPDATE_INTERVAL}
    restart: always
